export interface AugerData {
  id: string;
  name: string;
  zone: string;
  position: number;
  isRunning: boolean;
  throughput: number;
  targetThroughput: number;
  temperature: number;
  humidity: number;
  status: "optimal" | "warning" | "stopped" | "error";
}

// Hardcoded mock data to prevent hydration issues
export const mockAugerData: AugerData[] = [
  {
    id: "SA-001",
    name: "Raptor Sweep 1",
    zone: "Zone A",
    position: 45,
    isRunning: true,
    throughput: 78.5,
    targetThroughput: 80.0,
    temperature: 72.3,
    humidity: 48.7,
    status: "optimal",
  },
  {
    id: "SA-002",
    name: "Raptor Sweep 2",
    zone: "Zone A",
    position: 120,
    isRunning: true,
    throughput: 65.2,
    targetThroughput: 75.0,
    temperature: 69.8,
    humidity: 52.1,
    status: "warning",
  },
  {
    id: "SA-003",
    name: "Raptor Sweep 3",
    zone: "Zone A",
    position: 200,
    isRunning: false,
    throughput: 0.0,
    targetThroughput: 70.0,
    temperature: 68.1,
    humidity: 45.3,
    status: "stopped",
  },
  {
    id: "SA-004",
    name: "Raptor Sweep 4",
    zone: "Zone A",
    position: 315,
    isRunning: true,
    throughput: 92.1,
    targetThroughput: 90.0,
    temperature: 74.6,
    humidity: 49.8,
    status: "optimal",
  },
  {
    id: "SA-005",
    name: "Raptor Sweep 5",
    zone: "Zone B",
    position: 30,
    isRunning: true,
    throughput: 55.7,
    targetThroughput: 65.0,
    temperature: 71.2,
    humidity: 46.9,
    status: "warning",
  },
  {
    id: "SA-006",
    name: "Raptor Sweep 6",
    zone: "Zone B",
    position: 180,
    isRunning: true,
    throughput: 83.4,
    targetThroughput: 85.0,
    temperature: 73.5,
    humidity: 51.2,
    status: "optimal",
  },
  {
    id: "SA-007",
    name: "Raptor Sweep 7",
    zone: "Zone B",
    position: 270,
    isRunning: false,
    throughput: 0.0,
    targetThroughput: 60.0,
    temperature: 67.8,
    humidity: 44.1,
    status: "stopped",
  },
  {
    id: "SA-008",
    name: "Raptor Sweep 8",
    zone: "Zone B",
    position: 90,
    isRunning: true,
    throughput: 76.8,
    targetThroughput: 80.0,
    temperature: 70.9,
    humidity: 47.6,
    status: "optimal",
  },
  {
    id: "SA-009",
    name: "Raptor Sweep 9",
    zone: "Zone C",
    position: 135,
    isRunning: true,
    throughput: 42.3,
    targetThroughput: 55.0,
    temperature: 82.1,
    humidity: 58.7,
    status: "error",
  },
  {
    id: "SA-010",
    name: "Raptor Sweep 10",
    zone: "Zone C",
    position: 225,
    isRunning: true,
    throughput: 67.9,
    targetThroughput: 70.0,
    temperature: 69.4,
    humidity: 43.8,
    status: "optimal",
  },
  {
    id: "SA-011",
    name: "Raptor Sweep 11",
    zone: "Zone C",
    position: 300,
    isRunning: false,
    throughput: 0.0,
    targetThroughput: 75.0,
    temperature: 66.7,
    humidity: 41.2,
    status: "stopped",
  },
  {
    id: "SA-012",
    name: "Raptor Sweep 12",
    zone: "Zone C",
    position: 60,
    isRunning: true,
    throughput: 88.6,
    targetThroughput: 85.0,
    temperature: 75.3,
    humidity: 50.4,
    status: "optimal",
  },
  {
    id: "SA-013",
    name: "Raptor Sweep 13",
    zone: "Zone D",
    position: 150,
    isRunning: true,
    throughput: 71.2,
    targetThroughput: 75.0,
    temperature: 68.9,
    humidity: 46.1,
    status: "optimal",
  },
  {
    id: "SA-014",
    name: "Raptor Sweep 14",
    zone: "Zone D",
    position: 240,
    isRunning: true,
    throughput: 59.8,
    targetThroughput: 80.0,
    temperature: 77.6,
    humidity: 54.3,
    status: "warning",
  },
  {
    id: "SA-015",
    name: "Raptor Sweep 15",
    zone: "Zone D",
    position: 330,
    isRunning: false,
    throughput: 0.0,
    targetThroughput: 65.0,
    temperature: 65.2,
    humidity: 42.7,
    status: "stopped",
  },
  {
    id: "SA-016",
    name: "Raptor Sweep 16",
    zone: "Zone D",
    position: 75,
    isRunning: true,
    throughput: 94.7,
    targetThroughput: 95.0,
    temperature: 73.8,
    humidity: 48.9,
    status: "optimal",
  },
  {
    id: "SA-017",
    name: "Raptor Sweep 17",
    zone: "Zone E",
    position: 165,
    isRunning: true,
    throughput: 52.4,
    targetThroughput: 70.0,
    temperature: 79.3,
    humidity: 56.8,
    status: "warning",
  },
  {
    id: "SA-018",
    name: "Raptor Sweep 18",
    zone: "Zone E",
    position: 255,
    isRunning: true,
    throughput: 81.1,
    targetThroughput: 80.0,
    temperature: 71.7,
    humidity: 45.6,
    status: "optimal",
  },
  {
    id: "SA-019",
    name: "Raptor Sweep 19",
    zone: "Zone E",
    position: 345,
    isRunning: false,
    throughput: 0.0,
    targetThroughput: 85.0,
    temperature: 64.9,
    humidity: 40.3,
    status: "stopped",
  },
  {
    id: "SA-020",
    name: "Raptor Sweep 20",
    zone: "Zone E",
    position: 105,
    isRunning: true,
    throughput: 73.6,
    targetThroughput: 75.0,
    temperature: 70.1,
    humidity: 47.2,
    status: "optimal",
  },
  {
    id: "SA-021",
    name: "Raptor Sweep 21",
    zone: "Zone F",
    position: 195,
    isRunning: true,
    throughput: 66.8,
    targetThroughput: 65.0,
    temperature: 72.4,
    humidity: 49.1,
    status: "optimal",
  },
  {
    id: "SA-022",
    name: "Raptor Sweep 22",
    zone: "Zone F",
    position: 285,
    isRunning: true,
    throughput: 48.9,
    targetThroughput: 75.0,
    temperature: 84.2,
    humidity: 61.4,
    status: "error",
  },
  {
    id: "SA-023",
    name: "Raptor Sweep 23",
    zone: "Zone F",
    position: 15,
    isRunning: false,
    throughput: 0.0,
    targetThroughput: 70.0,
    temperature: 63.8,
    humidity: 39.7,
    status: "stopped",
  },
  {
    id: "SA-024",
    name: "Raptor Sweep 24",
    zone: "Zone F",
    position: 120,
    isRunning: true,
    throughput: 87.3,
    targetThroughput: 90.0,
    temperature: 74.1,
    humidity: 51.8,
    status: "optimal",
  },
];
